services:
  - type: web
    name: n8n
    env: docker
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: "5678"
      - key: N8N_PORT
        value: "5678"
      - key: GENERIC_TIMEZONE
        value: "America/Argentina/Buenos_Aires"
      - key: TZ
        value: "America/Argentina/Buenos_Aires"
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_HOST
        value: aws-1-us-east-2.pooler.supabase.com
      - key: DB_POSTGRESDB_PORT
        value: "6543"
      - key: DB_POSTGRESDB_USER
        value: postgres.dnbksebxogreauqsszrj
      - key: DB_POSTGRESDB_PASSWORD
        value: sd088359zVITFu1C
      - key: DB_POSTGRESDB_SSL_ENABLED
        value: "true"
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"
      - key: N8N_ENCRYPTION_KEY
        value: secure_n8n_key_777_qwerty
      - key: WEBHOOK_URL
        value: "https://n8n-e6fq.onrender.com"
      - key: N8N_DIAGNOSTICS_ENABLED
        value: "false"
      - key: N8N_PERSONALIZATION_ENABLED
        value: "false"
